import type { ReferenceScoreThreshold } from "./reference_score_policy";

const REFERENCE_SCORE_MINIMUM = 99;

export const MERMAID_VISUAL_ACCEPTED_SCORE_FLOORS: ReferenceScoreThreshold[] = [
  visualAccepted("03-classdiagram"),
  visualAccepted("04-sequencediagram"),
  visualAccepted("05-erdiagram"),
  visualAccepted("08-mindmap"),
  visualAccepted("09-architecture-beta"),
  visualAccepted("10-block-beta"),
  visualAccepted("11-c4"),
  visualAccepted("13-gitgraph"),
  visualAccepted("14-ishikawa-beta"),
  visualAccepted("20-requirementdiagram"),
  visualAccepted("21-sankey-beta"),
  visualAccepted("22-timeline"),
  visualAccepted("23-treeview-beta"),
  visualAccepted("24-treemap-beta"),
  visualAccepted("25-journey"),
  visualAccepted("27-wardley-beta"),
  visualAccepted("01-flowchart"),
  visualAccepted("02-graph"),
  visualAccepted("03-01-class-diagram-enumeration"),
  visualAccepted("03-02-class-diagram-inheritance"),
  visualAccepted("04-01-sequence-diagram-simple"),
  visualAccepted("04-02-sequence-diagram-activate-deactivate"),
  visualAccepted("04-02-sequence-diagram"),
  visualAccepted("05-01-er-diagram-simple"),
  visualAccepted("05-02-er-diagram-multi-entity"),
  visualAccepted("05-01-er"),
  visualAccepted("05-02-er"),
  visualAccepted("06-01-state-diagram-v2-failure-path"),
  visualAccepted("06-02-v2"),
  visualAccepted("06-03-v1"),
  visualAccepted("07-01-mindmap-simple"),
  visualAccepted("07-02-mindmap-icons"),
  visualAccepted("08-01-c4-context-simple"),
  visualAccepted("08-02-c4-context-full"),
  visualAccepted("08-03-c4-container"),
  visualAccepted("08-04-c4-component"),
  visualAccepted("08-04-c4"),
  visualAccepted("08-05-c4-dynamic"),
  visualAccepted("08-06-c4-deployment"),
  visualAccepted("08-05-c4"),
  visualAccepted("09-01-architecture-diagram-simple"),
  visualAccepted("09-02-architecture-diagram-multi-service"),
  visualAccepted("10-01-block-diagram-horizontal"),
  visualAccepted("10-02-block-diagram-vertical"),
  visualAccepted("10-02-block-beta"),
  visualAccepted("12-01-git-graph-simple"),
  visualAccepted("12-02-git-graph-multi-branch"),
  visualAccepted("13-01-ishikawa-diagram-3-categories"),
  visualAccepted("13-02-ishikawa-diagram-4-categories"),
  visualAccepted("14-01-kanban-simple"),
  visualAccepted("14-02-kanban-full"),
  visualAccepted("16-01-pie-chart-rendering-ownership"),
  visualAccepted("16-01-pie"),
  visualAccepted("16-02-pie"),
  visualAccepted("17-01-quadrant-chart-simple"),
  visualAccepted("17-02-quadrant-chart-campaigns"),
  visualAccepted("19-01-requirement-diagram-single"),
  visualAccepted("19-01-requirement-diagram"),
  visualAccepted("19-02-requirement-diagram-multi"),
  visualAccepted("20-02-sankey-large"),
  visualAccepted("21-01-timeline-phases"),
  visualAccepted("21-02-timeline-history"),
  visualAccepted("21-02-timeline"),
  visualAccepted("22-01-tree-view-simple"),
  visualAccepted("22-02-tree-view-file-system"),
  visualAccepted("23-01-treemap-flat"),
  visualAccepted("23-02-treemap-beta-nested"),
  visualAccepted("24-01-user-journey-diagram-preview"),
  visualAccepted("24-02-user-journey-working-day"),
  visualAccepted("25-01-venn-diagram-2-sets"),
  visualAccepted("25-02-venn-diagram-3-sets-with-styles"),
  visualAccepted("26-01-wardley-map-simple"),
  visualAccepted("26-02-wardley-map-full-with-notes"),
  acceptedScore("28-zen-uml", "ZenUMLも99点以上を品質下限として固定。"),
];

function visualAccepted(slug: string): ReferenceScoreThreshold {
  return acceptedScore(slug, "公式 reference との差分は99点以上だけを品質下限として固定。");
}

function acceptedScore(slug: string, reason: string): ReferenceScoreThreshold {
  return {
    slug,
    minScore: REFERENCE_SCORE_MINIMUM,
    reason,
  };
}
