import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { DrawioRuntimeBundleDefinition } from "../../crates/katana-diagram-renderer/src/markdown/diagram_runtime/source/drawio/runtime_definition";
import { MermaidRuntimeBundleDefinition } from "../../crates/katana-diagram-renderer/src/markdown/diagram_runtime/source/mermaid/runtime_definition";
import type {
  RuntimeBundleDefinition,
  RuntimeFragment,
  RuntimeFragmentTransform,
} from "../../crates/katana-diagram-renderer/src/markdown/diagram_runtime/source/shared/runtime_bundle";
import { ZenumlRuntimeBundleDefinition } from "../../crates/katana-diagram-renderer/src/markdown/diagram_runtime/source/zenuml/runtime_definition";

type RuntimeBundleMode = "write" | "check";

interface GeneratedBundle {
  readonly definition: RuntimeBundleDefinition;
  readonly outputPath: string;
  readonly content: string;
  readonly checksum: string;
}

class RuntimeBundleCommand {
  constructor(
    private readonly root: string,
    private readonly mode: RuntimeBundleMode,
  ) {}

  run(): void {
    const bundles = this.definitions().map((definition) => this.generate(definition));
    if (this.mode === "check") {
      this.checkGeneratedBundles(bundles);
      return;
    }
    this.writeGeneratedBundles(bundles);
  }

  private definitions(): RuntimeBundleDefinition[] {
    return [
      MermaidRuntimeBundleDefinition.create(),
      DrawioRuntimeBundleDefinition.create(),
      ZenumlRuntimeBundleDefinition.create(),
    ];
  }

  private generate(definition: RuntimeBundleDefinition): GeneratedBundle {
    const content = [
      this.generatedHeader(definition),
      ...definition.fragments.map((fragment) => this.fragmentContent(fragment)),
      this.entrypointContent(definition),
    ].join("\n");
    return {
      definition,
      outputPath: this.generatedPath(definition.outputFile),
      content,
      checksum: RuntimeBundleChecksum.digest(content),
    };
  }

  private generatedHeader(definition: RuntimeBundleDefinition): string {
    return [
      "// @generated by scripts/runtime-bundles/bundle-runtime.ts",
      `// bundle: ${definition.name}`,
      "",
    ].join("\n");
  }

  private fragmentContent(fragment: RuntimeFragment): string {
    const sourcePath = path.join(this.root, fragment.sourcePath);
    const source = fs.readFileSync(sourcePath, "utf8");
    return [`/* ${fragment.label} */`, this.transform(source, fragment.transform), ""].join("\n");
  }

  private transform(source: string, transform: RuntimeFragmentTransform): string {
    if (transform === "verbatim") {
      return source;
    }
    if (transform === "drawio-runtime-adapter-without-installer") {
      return this.replaceRequiredLine(source, "katanaInstallDrawioRuntimeAdapter();", "");
    }
    return this.replaceRequiredLine(source, "katanaRenderDrawioSvg();", "");
  }

  private replaceRequiredLine(source: string, needle: string, replacement: string): string {
    if (!source.includes(needle)) {
      throw new Error(`Runtime bundle transform target was not found: ${needle}`);
    }
    return source.replace(needle, replacement);
  }

  private entrypointContent(definition: RuntimeBundleDefinition): string {
    return [`/* ${definition.name}-runtime-entrypoint */`, definition.entrypoint.trim(), ""].join(
      "\n",
    );
  }

  private generatedPath(outputFile: string): string {
    return path.join(
      this.root,
      "crates",
      "katana-diagram-renderer",
      "src",
      "markdown",
      "diagram_runtime",
      "generated",
      outputFile,
    );
  }

  private checkGeneratedBundles(bundles: GeneratedBundle[]): void {
    const scratch = fs.mkdtempSync(path.join(os.tmpdir(), "kdr-runtime-bundles-"));
    try {
      for (const bundle of bundles) {
        const expected = fs.readFileSync(bundle.outputPath, "utf8");
        const scratchPath = path.join(scratch, bundle.definition.outputFile);
        fs.writeFileSync(scratchPath, bundle.content, "utf8");
        if (expected !== bundle.content) {
          throw new Error(
            `Runtime bundle is stale: ${path.relative(this.root, bundle.outputPath)} differs from ${scratchPath}`,
          );
        }
      }
      this.checkChecksumManifest(bundles);
    } finally {
      fs.rmSync(scratch, { recursive: true, force: true });
    }
  }

  private checkChecksumManifest(bundles: GeneratedBundle[]): void {
    const expected = this.checksumManifest(bundles);
    const manifestPath = this.checksumManifestPath();
    const actual = fs.readFileSync(manifestPath, "utf8");
    if (actual !== expected) {
      throw new Error(`Runtime bundle checksum manifest is stale: ${manifestPath}`);
    }
  }

  private writeGeneratedBundles(bundles: GeneratedBundle[]): void {
    for (const bundle of bundles) {
      fs.mkdirSync(path.dirname(bundle.outputPath), { recursive: true });
      fs.writeFileSync(bundle.outputPath, bundle.content, "utf8");
    }
    fs.writeFileSync(this.checksumManifestPath(), this.checksumManifest(bundles), "utf8");
  }

  private checksumManifest(bundles: GeneratedBundle[]): string {
    return bundles
      .map((bundle) => `${bundle.checksum}  ${bundle.definition.outputFile}`)
      .join("\n")
      .concat("\n");
  }

  private checksumManifestPath(): string {
    return path.join(
      this.root,
      "crates",
      "katana-diagram-renderer",
      "src",
      "markdown",
      "diagram_runtime",
      "generated",
      "runtime-bundles.sha256",
    );
  }
}

class RuntimeBundleChecksum {
  static digest(content: string): string {
    return crypto.createHash("sha256").update(content).digest("hex");
  }
}

class RuntimeBundleCli {
  static parse(argv: string[]): RuntimeBundleMode {
    if (argv.includes("--write")) {
      return "write";
    }
    if (argv.includes("--check")) {
      return "check";
    }
    throw new Error("Usage: bun run scripts/runtime-bundles/bundle-runtime.ts --write|--check");
  }
}

new RuntimeBundleCommand(process.cwd(), RuntimeBundleCli.parse(process.argv.slice(2))).run();
