import fs from "node:fs";
import path from "node:path";
import { DrawioRuntimeBundleDefinition } from "#drawio/runtime_definition";
import { MermaidRuntimeBundleDefinition } from "#mermaid/runtime_definition";
import type { RuntimeBundleDefinition } from "#shared/runtime_bundle";
import { ZenumlRuntimeBundleDefinition } from "#zenuml/runtime_definition";
import { MathJaxRuntimeBundleDefinition } from "../../crates/katana-render-runtime/src/markdown/diagram_runtime/source/mathjax/runtime_definition";
import { RuntimeBundleChecks, renderRuntimeBundleManifest } from "./runtime-bundle-checks";
import { runtimeBundleChecksum } from "./runtime-bundle-checksum";
import { RuntimeBundlePaths } from "./runtime-bundle-paths";
import type { GeneratedBundle, RuntimeBundleMode } from "./runtime-bundle-types";
import { RuntimeRollupBundler } from "./runtime-rollup-bundler";

export class RuntimeBundleCommand {
  private readonly bundler: RuntimeRollupBundler;
  private readonly paths: RuntimeBundlePaths;

  constructor(
    root: string,
    private readonly mode: RuntimeBundleMode,
  ) {
    this.paths = new RuntimeBundlePaths(root);
    this.bundler = new RuntimeRollupBundler(root);
  }

  async run(): Promise<void> {
    const bundles = await Promise.all(
      this.definitions().map((definition) => this.generate(definition)),
    );
    if (this.mode === "check") {
      new RuntimeBundleChecks(this.paths).checkGeneratedBundles(bundles);
      return;
    }
    this.writeGeneratedBundles(bundles);
  }

  private definitions(): RuntimeBundleDefinition[] {
    return [
      MermaidRuntimeBundleDefinition.create(),
      DrawioRuntimeBundleDefinition.create(),
      ZenumlRuntimeBundleDefinition.create(),
      MathJaxRuntimeBundleDefinition.create(),
    ];
  }

  private async generate(definition: RuntimeBundleDefinition): Promise<GeneratedBundle> {
    const bundle = await this.bundler.bundle(definition);
    const content = [this.generatedHeader(definition), bundle, ""].join("\n");
    return {
      definition,
      outputPath: this.paths.generatedPath(definition.outputFile),
      content,
      checksum: runtimeBundleChecksum(content),
    };
  }

  private generatedHeader(definition: RuntimeBundleDefinition): string {
    return [
      "// @generated by scripts/runtime-bundles/bundle-runtime.ts",
      `// bundle: ${definition.name}`,
      "",
    ].join("\n");
  }

  private writeGeneratedBundles(bundles: GeneratedBundle[]): void {
    for (const bundle of bundles) {
      fs.mkdirSync(path.dirname(bundle.outputPath), { recursive: true });
      fs.writeFileSync(bundle.outputPath, bundle.content, "utf8");
    }
    fs.writeFileSync(
      this.paths.checksumManifestPath(),
      renderRuntimeBundleManifest(bundles),
      "utf8",
    );
  }
}
